In [1]:
#database mysql connectivity with using python
import sqlite3
com = sqlite3.connect("College.db")
cursor = com.cursor()
cursor.execute('''
CREATE TABLE IF NOT EXISTS student (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    age INTEGER,
    grade TEXT
)
''')
com.commit()
print("Table created successfully.")

Table created successfully.


In [6]:
def insert_student(name, age, grade):
    cursor.execute("INSERT INTO student (name, age, grade) VALUES (?, ?, ?)", (name, age, grade))
    com.commit()
    print("Student inserted successfully.")

insert_student('Janvi', 18, 'A')
insert_student('Kush', 20, 'B')

Student inserted successfully.
Student inserted successfully.


In [7]:
def fetch_students():
    cursor.execute("SELECT * FROM student")
    rows = cursor.fetchall()
    for row in rows:
        print(row)

fetch_students()

(1, 'Riya', 20, 'A')
(2, 'Sneha', 22, 'B')
(3, 'Janvi', 18, 'A')
(4, 'Kush', 20, 'B')
(5, 'Janvi', 18, 'A')
(6, 'Kush', 20, 'B')


In [8]:
def update_student(student_id, new_name, new_age, new_grade):
    cursor.execute("UPDATE student SET name=?, age=?, grade=? WHERE id=?", (new_name, new_age, new_grade, student_id))
    com.commit()
    print("Student updated successfully.")
update_student(1, 'Janvi Jasoria', 21, 'A+')

Student updated successfully.


In [9]:
def delete_student(student_id):
    cursor.execute("DELETE FROM student WHERE id=?", (student_id,))
    com.commit()
    print("Student deleted successfully.")

delete_student(2)

Student deleted successfully.


In [10]:
com.close()
print("Database connection closed.")

Database connection closed.


In [11]:
#numpy
import numpy as np
# array
a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])
print(a)
print(b)

[1 2 3]
[[1 2]
 [3 4]]


In [12]:
twoD = np.array([[1,2,3],[4,5,6]])
#array function
print(twoD.shape)
print(twoD.size)
print(twoD.ndim)
print(twoD.dtype)

(2, 3)
6
2
int64


In [13]:
#reshape
twoD = np.array([1,2,3,4,5,6])
print(twoD.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [14]:
import numpy as np
#copy
a = np.array([1, 2, 3])
b = a.copy()
c = a.view()
a[0] = 99
print(b)  # [1 2 3] (copy remains same)
print(c)  # [99 2 3] (view reflects change)

[1 2 3]
[99  2  3]


In [17]:
twoD = np.array([[1,2,3],[4,5,6]])
print("Zeros Matrix: \n",np.zeros((2,3)))
print("Ones Matrix: \n",np.ones((3,3)))
print("Identity Matrix: \n",np.eye(2,3)) 
print("Full Matrix:\n",np.full((2,3),7))
print("Arranged Matrix:\n",np.arange(1,5,2))
print("linspace Matrix:\n",np.linspace(1,7,3))

Zeros Matrix: 
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Matrix: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]]
Full Matrix:
 [[7 7 7]
 [7 7 7]]
Arranged Matrix:
 [1 3]
linspace Matrix:
 [1. 4. 7.]


In [18]:
a = np.array([23,3,2])
b = np.array([3,4,2])
#mathematical operation
print("Addition of matrix: ",a+b)
print("Multiplication of corresponding elements: ",a * b)
print("Exponent Matrix: ",b ** 2)
print("Square of a Matrix: ",np.sqrt(a))
print("Mean of a Matrix: ",np.mean(b))

Addition of matrix:  [26  7  4]
Multiplication of corresponding elements:  [69 12  4]
Exponent Matrix:  [ 9 16  4]
Square of a Matrix:  [4.79583152 1.73205081 1.41421356]
Mean of a Matrix:  3.0


In [19]:
twoD = np.array([[1,6,3],[4,9,6]])
print(np.sum(twoD))
print(np.min(twoD))
print(np.max(twoD))
print(np.sum(twoD,axis=0)) #column wise sum
print(np.sum(twoD,axis=1)) #row wise sum
print(np.sort(twoD))
print(twoD.flatten()) # converted to array
print(twoD.T)

29
1
9
[ 5 15  9]
[10 19]
[[1 3 6]
 [4 6 9]]
[1 6 3 4 9 6]
[[1 4]
 [6 9]
 [3 6]]


In [20]:
#matrix multiplication 
b = np.array([[1,6,3],[4,9,6]])
a = np.array([[2,3],[9,1]])
print(np.dot(a,b))

[[14 39 24]
 [13 63 33]]


In [21]:
#metplotlib
#seaborn

In [22]:
import pandas as pd

In [23]:
#from dictionary
data = {
    "Name" : ["Janvi","Kush"], # dictionary with multiple values 
    "Age" : [18,20]}

print(data)

{'Name': ['Janvi', 'Kush'], 'Age': [18, 20]}


In [24]:
# Que1: Create a NumPy array of integers from 0 to 10.
print(np.arange(0,11))

[ 0  1  2  3  4  5  6  7  8  9 10]


In [25]:
# Que2: Create an array of 10 zeros and change the 5th value to 1.
arr = np.zeros((10))
arr[5] = 1
print(arr)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [26]:
# Que3: Generate an array of 10 ones.
print(np.ones((10)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [27]:
# Que4: Create a 1D array of 20 equally spaced numbers between 0 and 1.
print(np.linspace(0,1,20))

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [28]:
# Que5: Create a 3x3 identity matrix.
print(np.eye(3,3)) 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
# Que6: Create a 4x4 matrix with values from 0 to 15.
arr = np.arange(0, 16).reshape(4, 4)
print("Matrix 4x4:\n", arr)

Matrix 4x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [30]:
# Que7: Generate a 5x5 matrix with random values.
arr = np.random.randint(1, 101, size=(5, 5))
print("Matrix 5x5:\n", arr)

Matrix 5x5:
 [[23 62  5 41 62]
 [49 29 13 59 29]
 [94 86  4 92 34]
 [31 83  3 79  8]
 [48 45 85 86 32]]


In [31]:
# Que8: Reverse the elements of an array.
arr = np.array([78,21,90,12])
print(np.flip(arr))

[12 90 21 78]


In [32]:
# Que9: Flatten a 2D array to 1D.
twoD = np.array([[21,34],[89,23]]) # 2D
print(twoD.flatten()) # 1D

[21 34 89 23]


In [33]:
# Que10: Extract even numbers from an array
arr = np.array([78,21,90,12])
for i in arr:
    if i%2==0:
        print(i)

78
90
12
